# Generated by Django 3.0.5 on 2020-04-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('fizyka', 'fizyka'), ('matematyka', 'matematyka'), ('angielski', 'angielski')], max_length=10)),
                ('time', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.Account')),
            ],
        ),
    ]
