# Generated by Django 3.0.5 on 2020-04-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='time',
        ),
    ]
